name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix profile add nixpkgs#typst
    - run: ./bin/cv check
