name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix develop -c ./bin/cv check-all
